### ISSUE TITLE
Allow multiple lines in text message

### ISSUE THREAD

**Issue by spaceraccoon** [spaceraccoon/road-sign-manager#33]
Modify `transformText` so that it instead of a string `text`, it takes an array `lines` of up to size 2 or 3 (up to you) with each element in the array corresponding to a line of text. It returns a binary string with the corresponding display of the correct number of lines. There is no need to validate the number of lines since this will be done in the route function. Since `fillText` doesn't support multiple lines, one solution is creating separate canvasses or buffers.

**Comment by anniezhou301** [comment]
Can you clarify? Should transformText return a binary string that, visually, will look separated into 2 rows (if there are two lines)? For instance, if the text was, "Hello World" and the lines argument was 2, the resulting string would look something like:

HELLO
WORLD

in visual binary. If this is the case, what would that text look like if the lines input was 3 lines?

**Comment by spaceraccoon** [comment]
Sorry, I've modified the spec to work more logically. It now just takes one argument, which is an array of strings (max length 2 or 3 up to you) and you parse each element as a line. So on the client side, instead of one textbox, they have 2 or 3 textboxes, each corresponding to a line. If they enter text only in the first textbox, then only an array of length 1 is sent to transformText.

**Comment by anniezhou301** [comment]
I can't test my code because I think the most updated version is broken. It keeps giving me the error

ypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:102:11)
    at Object.urlParse [as parse] (url.js:96:5)
    at dispatchHttpRequest (/Users/anniezhou/Documents/road-sign-manager/node_modules/axios/lib/adapters/http.js:57:22)
    at Promise (<anonymous>)
    at httpAdapter (/Users/anniezhou/Documents/road-sign-manager/node_modules/axios/lib/adapters/http.js:18:10)
    at dispatchRequest (/Users/anniezhou/Documents/road-sign-manager/node_modules/axios/lib/core/dispatchRequest.js:59:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by spaceraccoon** [comment]
You need to have a .env file in your root folder based on `.env.sample`. I've emailed you the one I'm using. I had that error on a fresh copy before filling up `.env`.

**Comment by anniezhou301** [comment]
I'm stuck :/ can you help me debug? The current code in lines works with one input (and it works with three inputs if you expand the code to fit for three lines). But the POST doesn't work with exactly two lines. The binary string is created properly (checked by a console.log at the bottom of transformText), it just doesn't send through axios in message.js. Overall, I get the error

{ Error: Request failed with status code 400
    at createError (/Users/anniezhou/Documents/road-sign-manager/node_modules/axios/lib/core/createError.js:16:15)...

I'm at a complete loss as to how to fix this.

**Comment by spaceraccoon** [comment]
I'll take a look! Hang tight.

**Comment by spaceraccoon** [comment]
Hey Annie,

Got a chance to look - the issue was `27 / lines.length`. When lines is an even number, the result is 13 (JS gives the integer quotient and doesn't account for floats). So your final output is of size 96 * 26, which is smaller than the 96 * 27 required by the simulator. This is why it works for 1 and 3, but not 2. What you need to do is pad the output with 0s for 96*(remainder) before returning it:

```
var remainder = process.env.DISPLAY_HEIGHT % lines.length;
  for (var y = 0; y < remainder; y++) {
    for (var x = 0; x < process.env.DISPLAY_WIDTH; x++) {
      answer += 0;
    }
  }
```

I've made these and a couple of style changes. You can check out the diff at https://github.com/spaceraccoon/road-sign-manager/commit/e543fe17e82d892e71cd9d1fd11a4d05e6ba77d2. Remember to use 2 spaces for tabs.

Pull this commit locally, make any other changes, then commit, push, and make a pull request as usual :)

Good work!
